version: '3.8'
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  hatinapura:
    container_name: "hastinapura-backend"
    image: hastinapura
    depends_on:
      - localstack
      - dynamodb-local
    ports:
      - "127.0.0.1:8080:8080"            # LocalStack Gateway
    environment:
      APP_ENV: 'docker'
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  app-node:
    image: amazon/aws-cli
    container_name: app-node
    depends_on:
      - dynamodb-local
      - localstack
    ports:
      - "9080:9080"
    environment:
      AWS_REGION: ap-south-1
      AWS_ACCESS_KEY_ID: 'DUMMY'
      AWS_SECRET_ACCESS_KEY: 'DUMMY'
    command:
#      dynamodb describe-limits --endpoint-url http://dynamodb-local:8000 --region ap-south-1
      dynamodb list-tables --endpoint-url http://dynamodb-local:8000 --region ap-south-1
#      dynamodb scan --table-name otp --endpoint-url http://dynamodb-local:8000 --region ap-south-1
#      dynamodb scan --table-name Contacts --endpoint-url http://dynamodb-local:8000 --region ap-south-1
#      s3 mb s3://myfirstbucket --endpoint-url http://localstack-main:4566 --region ap-south-1
#      s3 ls  --endpoint-url http://localstack-main:4566
#      s3 ls s3://myfirstbucket  --endpoint-url http://localstack-main:4566
